# Azure deployment workflow for white-label chat application
name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create deployment package
        run: |
          # Create a clean deployment directory
          mkdir deployment
          
          # Copy essential files
          cp production_wsgi.py deployment/
          cp requirements.txt deployment/
          cp auth.html deployment/
          
          # Copy application directories
          cp -r app deployment/
          cp -r static deployment/
          
          # Create deployment zip
          cd deployment
          zip -r ../deployment.zip .
          cd ..

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'white-label-chat-km'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deployment.zip
